name: CI Nginx Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Connexion GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Générer le tag SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Vérifier les fichiers essentiels
        run: |
          test -f Dockerfile
          test -f nginx/index.html
          test -f nginx/nginx.conf

      - name: Construire l'image Docker
        run: |
          docker build \
            -t nginx-ci-cd-tp \
            -t ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.sha_short }} .

      - name: Tester la configuration Nginx
        run: docker run --rm nginx-ci-cd-tp nginx -t

      - name: Lancer le conteneur
        run: docker run -d --name nginx-test -p 8080:80 nginx-ci-cd-tp

      - name: Tester la réponse HTTP
        run: |
          sleep 3
          curl -f http://localhost:8080

      - name: Tester le endpoint health
        run: curl -f http://localhost:8080/health

      - name: Publier l'image dans GHCR
        run: docker push ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.sha_short }}

  deploy-production:
    needs: build-test
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Validation manuelle effectuée
        run: echo "Déploiement production validé manuellement"
